import 'dart:io';
import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;
import 'tables.dart';

// part 'database.g.dart'; // This will be generated by build_runner

// Assuming the generated classes will be named SleepSession, Setting, SyncQueueData, SensorLog
// We define the database class

// @DriftDatabase(tables: [SleepSessions, Settings, SyncQueue, SensorLogs])
class AppDatabase /* extends _$AppDatabase */ {
  // Normally this extends the generated class.
  // For now, we mock the basic structure to avoid syntax errors before generation
  
  // AppDatabase() : super(_openConnection());
  AppDatabase();

  /*
  @override
  int get schemaVersion => 1;
  */
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'minnasleep_db.sqlite'));
    return NativeDatabase.createInBackground(file);
  });
}
